environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37

install:
  - pip install --upgrade --user pip
  - pip install tox

build: false

test_script:
  - tox

branches:
  only:
    - master
    - /^.*-maintenance$/

cache:
  - '%LOCALAPPDATA%\pip\Cache'
